services:
  
  oxalate-neo4j:
    image: neo4j:latest
    volumes:
        - oxalate_neo4j_data:/logs
        - oxalate_neo4j_data:/config
        - oxalate_neo4j_data:/data
        - oxalate_neo4j_data:/plugins
    environment:
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_PLUGINS=["apoc"]
    env_file:
      - ../../.env.dev
    ports:
      - "7687:7687"
      - "7474:7474"
    restart: always
  
  oxalate-paradedb:
    image: paradedb/paradedb:latest
    #   POSTGRES_USER: ${POSTGRES_USER:-root}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    #   POSRES_DB: ${POSTGRES_DB:-Oxalate}
    env_file:
      - ../../.env.dev
    volumes:
      - oxalate_paradedb_data:/var/lib/postgresql
    labels:
      kompose.init.containers.command: "echo Initializing harvester postgres database"
      kompose.controller.expose.port: true
    ports:
      - "6666:5432"
    networks:
      - app-network
    restart: unless-stopped

  oxalate-redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command: >
      redpanda start
      --smp 1
      --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      --advertise-kafka-addr internal://oxalate-redpanda:9092,external://localhost:19092
      --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      --advertise-pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      --mode dev-container
    ports:
      - "19092:19092"
      - "18082:18082"
    networks:
      - app-network
    env_file:
      - ../../.env.dev

  oxalate-dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ports:
      - "6379:6379"
    volumes:
      - oxalate_dragonfly_data:/data


networks:
  app-network:
    driver: bridge

volumes:
  oxalate_paradedb_data:
  oxalate_redpanda_data:
  oxalate_neo4j_data:
  oxalate_dragonfly_data:
