env:
    postgres_user: ENC[AES256_GCM,data:VZTrnyGCDn4dCx/fY755ZyZdAemt8A==,iv:PNPtrV72hJJ55X0q3PF2K1u5OthrmYmEppNLGHZafLk=,tag:WTIg3zQ+JvLLyXaYvsEBRw==,type:str]
    postgres_password: ENC[AES256_GCM,data:kIbxDbN+ayBoeZ4bxsUCZD3f1UfSIiVeENInO4kjsA==,iv:BWJX3xVOTUa4Pf2vJHYJrEONhRRYla05gg2RKnbZCH4=,tag:4uytCL2a5xtfRy7pHLR2dQ==,type:str]
    neo4j_auth: ENC[AES256_GCM,data:MO1RRJcJuJ+fHqoX1FILRwAsPF8j34Oa2e8axzkjhoBCHU4K8KYRdKZ9rf5H9/15O4o=,iv:biHvrSavlMzCfeBaAw+psShDOR5nHmn6JA+yS/6y/vY=,tag:U2JVAdwHycstTt6A0WKffQ==,type:str]
sops:
    age:
        - recipient: age1xey6v96y8zjmz7uur5nvhcgjfnpy46thway4ugqgmgpzwcd7myxspefxwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZlcvOVI2SnN4cDdwTDRr
            NzVQN1ZzSmVrakJaVHI3OENhZlhoZEdQSlNzClBTRnhlaDFhVFVRYWFBZEZMVks2
            TU1zZXVzREtsa1l2QlpWSUZKYzg2YXcKLS0tIGZGV2U0UkwwTFoyWitYZGZoU2Vp
            MGRCc2NFc0VLVW14S0N3NnhVY1MrUEEKuKyIUz9pqKMMg6fv0YP95rnbmA4pG4FR
            u78+LLCvWggauL4igVY+O3ffcF2taZoKBO180SQE44YzI/97WdmIUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T08:08:38Z"
    mac: ENC[AES256_GCM,data:xFX3L42jckPRAMWWFwHIjO0TQ+Z0ewa3x3A1hU+Fmhz8mvMG7XN9I0pd5icSjwBb7c88rQxliK8X7zAk0A7BVsPuRDUpP00C0qouvV3PEUIu6qx8EgRTmWQLMP9ETI3ModOaxAUmTQJl8EOd89KvImRxR7kWAQZvNV1K3qhnFmk=,iv:NDbx8rAVGfzjJCLzUQCELbcppONvZORPpsKXK9dEGyw=,tag:f/FTzN5DXfMlDLZZ85Tnzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
